<a href="https://colab.research.google.com/github/1oneweeek/DALC_Scala/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [1]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기# 넘파이 패키지를 불러오기 np로 줄여쓰기
import numpy as np

## array 정의 및 생성

In [2]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:

a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 배열 구성

In [4]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기
b = np.full((3, 4), 2.71)
b

array([[2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71]])

In [5]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기
c = np.arange(0, 10, 2)
c

array([0, 2, 4, 6, 8])

In [6]:
# linespace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하기
d = np.linspace(0, 1, 4)
d

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [7]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기
e = np.random.randint(0, 100, (2, 2))
e

array([[63, 40],
       [60, 83]])

## 배열 인덱싱

In [8]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기
print(a[2], a[-3])

3 8


In [9]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
print(a[3:9])

[4 5 6 7 8 9]


## 배열 재구조화

In [10]:
#차원의 개수 알아보는 함수
x = np.random.randint(10, size = (3, 4, 5))
x.ndim

3

In [11]:
#차원의 크기 알아보는 함수
x.shape

(3, 4, 5)

In [12]:
#전체 배열크기 알아보는 함수
x.size

60

In [13]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성
x = np.arange(10)
x[4:7]

array([4, 5, 6])

In [14]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)
z = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

In [17]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)
z = np.arange(1, 10).reshape(3, 3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 배열 결합

In [18]:
#두개의 배열 결합하기

In [19]:
#수직으로 두개의 배열 결합하기
x = np.array([1, 2, 3])
y = np.array([[4, 5, 6], [7, 8, 9]])
v = np.vstack([x, y])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#수평으로 두개의 배열 결합하기
k = np.array([[99], [99]])
z = np.hstack([y, k])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

## 배열 분할

In [21]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기
x = [1, 2, 3, 49, 52, 71, 99]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [49 52] [71 99]


In [22]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
u = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(u, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# Numpy 심화

## 유니버셜함수

In [23]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
a.shape

(3, 4)

In [27]:
a.ndim # len(a.shape)와 같습니다

2

In [28]:
a.size

12

In [29]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

array([[4.68764917e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [30]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [31]:
# x = np.array([-10, -5, 0, 3, 7])
# x에 있는 배열을 모두 양의 정수로 반환하기
np.abs(x)

array([ 1,  2,  3, 49, 52, 71, 99])

In [32]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기
print("ln(x) =", np.log10(x))

ln(x) = [0.         0.30103    0.47712125 1.69019608 1.71600334 1.85125835
 1.99563519]


## 집계함수

In [33]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
힌트: "np.absolute(x)"
np.abs(x)


array([2, 1, 0, 1, 2])

In [34]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
print(" 코사인 함수 =", np.cos(theta))
print("탄젠트 함수= ", np.tan(theta)) 



theta= [0.         1.57079633 3.14159265]
 코사인 함수 = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
탄젠트 함수=  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [35]:
#역삼각함수
x = [-1, 0, 1]
print("역 사인함수=", np.arcsin(x))
print("역 코사인함수=", np.arccos(x))
print("역 탄젠트함수=", np.arctan(x))

역 사인함수= [-1.57079633  0.          1.57079633]
역 코사인함수= [3.14159265 1.57079633 0.        ]
역 탄젠트함수= [-0.78539816  0.          0.78539816]


In [36]:
#로그함수
x=[1,2,4,10]
print("자연로그=",np.log(x))
print("밑이2인 로그함수=",np.log2(x))
print("밑이 10인 로그함수=", np.log10(x))

자연로그= [0.         0.69314718 1.38629436 2.30258509]
밑이2인 로그함수= [0.         1.         2.         3.32192809]
밑이 10인 로그함수= [0.         0.30103    0.60205999 1.        ]


In [37]:
#지수함수
x=[1,2,3]
print("e^x=", np.exp(x))
print("2^x", np.exp2(x))
print("3^x=",np.power(3, x))

e^x= [ 2.71828183  7.3890561  20.08553692]
2^x [2. 4. 8.]
3^x= [ 3  9 27]


In [38]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [39]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [40]:
#reduce 함수
x=np.arange(1,5)
np.add.reduce(x)

10

In [41]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=",np.min(s))
print("s의최댓값=",np.max(s))


s의최솟값= 0.0009204219868518271
s의최댓값= 0.9993432009637743


In [42]:
#axis 인자
"axis=0: 열기준 집계연산"
"axis=1: 행기준 집계연산"
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"

'axis=none: 배열 내 모든 요소의 집계연산axis 인자'

In [43]:
m= np.random.random((3,4))
print(m)

[[0.21179472 0.78715039 0.52716983 0.17455221]
 [0.80137006 0.40283985 0.88308687 0.98349678]
 [0.22037385 0.44964191 0.62764035 0.18392163]]


## 브로드캐스팅 연산

In [44]:
# 크기가 같은 어레이의 연산을 하기
x = np.array([0, 1, 2])
y = np.array([3, 3, 3])
x + y

array([3, 4, 5])

In [45]:
# 배열의 크기를 늘려서 연산하기
x = np.array([0, 1, 2])
M = np.ones((3, 3))
x + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 비교연산자

In [46]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기
import numpy as np
x = np.arange(10)
np.any(x < 5)

True

In [47]:
# all함수를 이용하여 true산출 코드 만들기
import numpy as np
x = np.arange(10)
np.all(x < 10)

True

In [48]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기
a = np.random.randint(1, 5, 5)
b = np.random.randint(1, 5, 5)
print(a, b)
a==b

[4 2 3 3 1] [1 4 3 1 2]


array([False, False,  True, False, False])

## 팬시 인덱싱

In [49]:
#배열을 생성하여 인덱싱하기
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱
b = np.array([0, 1, 2])
a[b]

array([0, 1, 2])

## 정렬 

In [51]:
#np.sort함수를 이용하여 복사하기
x = np.array([4, 1, 5, 2, 3])
print(x, np.sort(x))

[4 1 5 2 3] [1 2 3 4 5]


In [52]:
#변수.sort함수를 이용하여 정렬하기
x = np.array([4, 1, 5, 2, 3])
x.sort()
print(x)

[1 2 3 4 5]


In [53]:
#np.arsort함수 이용하여 정렬 요소의 인덱스를 반환하기
x = np.array([4, 1, 5, 2, 3])
i = np.argsort(x)
print(i)

[1 3 4 0 2]


In [54]:
#x_reverse를 이용하여 내림차순
x = np.array([4, 1, 5, 2, 3])
x_reverse = np.sort(x)[::-1]
print(x_reverse)

[5 4 3 2 1]


In [55]:
#axis를 이용하여 각 열을 기준으로 정렬하기
X = np.array([[2, 0, 6],
             [7, 3, 4],
             [1, 5, 3]])
np.sort(X, axis = 0)

array([[1, 0, 3],
       [2, 3, 4],
       [7, 5, 6]])

In [56]:
#axis를 이용하여 각 행을 기준으로 정렬하기#axis를 이용하여 각 행을 기준으로 정렬하기
X = np.array([[2, 0, 6],
             [7, 3, 4],
             [1, 5, 3]])
np.sort(X, axis = 1)

array([[0, 2, 6],
       [3, 4, 7],
       [1, 3, 5]])