<a href="https://colab.research.google.com/github/1oneweeek/DALC_Scala/blob/main/%EC%8A%A4%ED%84%B0%EB%94%94numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5]
data2 = [6, 5, 4, 3, 2, 1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [3]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [4]:
ar2 = np.array(data1, dtype='float32')
ar2

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
ar3 = np.array([range(i, i+3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [7]:
ar4 = np.full((3, 5), 3.14)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
ar6 = np.linspace(0, 1, 3)
ar6

array([0. , 0.5, 1. ])

In [10]:
ar7 = np.random.random((3, 3))
ar7

array([[0.39021285, 0.37180408, 0.16385065],
       [0.97203879, 0.21851364, 0.54560892],
       [0.32372607, 0.24371375, 0.81692424]])

In [11]:
ar8 = np.random.randint(0, 100, (3, 3))
ar8

array([[ 8, 99, 89],
       [84,  7, 43],
       [60, 27, 69]])

In [12]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
x = np.random.randint(10, size = (3, 4, 5))
x

array([[[8, 7, 0, 4, 4],
        [2, 9, 7, 5, 8],
        [4, 6, 5, 4, 7],
        [7, 4, 1, 1, 1]],

       [[0, 6, 4, 1, 1],
        [9, 7, 6, 2, 5],
        [4, 4, 7, 4, 2],
        [9, 9, 0, 7, 8]],

       [[4, 1, 8, 4, 7],
        [0, 2, 5, 0, 4],
        [0, 9, 4, 0, 8],
        [3, 8, 3, 8, 6]]])

In [15]:
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)

x ndim: 3
x shape: (3, 4, 5)
x size: 60


In [16]:
y = np.array([2, 4, 6, 8, 10])
print(y[0], y[-2])

2 8


In [18]:
z = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
print(z[1, 0])

3


In [19]:
z[0, 0]=12
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [20]:
x = np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [22]:
x = np.arange(10)
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x = np.arange(10)
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
z = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

In [25]:
z = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
z[:3, :2]

array([[2, 4],
       [3, 6]])

In [26]:
z = np.arange(1, 10).reshape(3, 3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y])
z

array([1, 2, 3, 3, 2, 1])

In [31]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], [7, 8, 9]])
v = np.vstack([x, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
y = np.array([[99], [99]])
z = np.hstack([grid, y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [34]:
x = [1, 2, 3, 77, 77, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


In [36]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
