<a href="https://colab.research.google.com/github/1oneweeek/DALC_Scala/blob/main/%EC%8A%A4%ED%84%B0%EB%94%94pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas
pandas.__version__

'1.1.5'

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1]

0.5

In [7]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data['b']

0.5

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
data[5]

0.5

In [13]:
population_dict = {'California' : 38332521,
                   'Texas' : 26448393,
                   'New York' : 19651127,
                   'Florida' : 19552860,
                   'Illinois' : 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448393
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [15]:
population['California':'Florida']

California    38332521
Texas         26448393
New York      19651127
Florida       19552860
dtype: int64

In [16]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [17]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [18]:
dic_data = {2:'a', 1:'b', 3:'c'}
dic_data

{1: 'b', 2: 'a', 3: 'c'}

In [20]:
pd.Series({2: 'a', 1:'b', 3:'c'}, index = [3, 2])

3    c
2    a
dtype: object

In [21]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York' : 141297, 
             'Florida': 170312, 'Illinois': 149995 }
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [22]:
states = pd.DataFrame({'population':population,
                       'area':area})
states

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

In [25]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [26]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448393
New York      19651127
Florida       19552860
Illinois      12882135

In [27]:
pd.DataFrame(population, index=['Texas'], columns = ['population'])

population
Texas    26448393

In [28]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [29]:
pd.DataFrame({'population':population,
              'area' : area})

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [31]:
pd.DataFrame(np.random.rand(3,2),
             columns = ['foo', 'bar'],
             index = ['a', 'b', 'c'])

foo       bar
a  0.426286  0.723597
b  0.808327  0.626165
c  0.652864  0.814738

여기서부터 2차시

In [33]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [34]:
ind[1]

3

In [35]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [37]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [39]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB # 교집합

Int64Index([3, 5, 7], dtype='int64')

In [40]:
indA | indB # 합집합

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [41]:
indA ^ indB # 대칭 차

Int64Index([1, 2, 9, 11], dtype='int64')

In [42]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [43]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [44]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [45]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [46]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [47]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [48]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [50]:
data.loc['a']

0.25

In [51]:
data.loc['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [52]:
data.iloc[1]

0.5

In [53]:
data.iloc[1:3]

b    0.50
c    0.75
dtype: float64

In [66]:
import pandas as pd
area = pd.Series({'California': 423967, 'Texas': 695662, 
                  'New York' : 141297, 'Florida': 170312, 
                  'Illinois': 149995})
pop = pd.Series({'California' : 38332521,'Texas' : 26448393,
                   'New York' : 19651127, 'Florida' : 19552860,
                   'Illinois' : 12882135})
data = pd.DataFrame({'area' : area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448393
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [58]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [59]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [67]:
states['density'] = states['pop'] / states['area']
states

KeyError: ignored

In [68]:
states.values

array([[38332521,   423967],
       [26448393,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [69]:
states.T

California     Texas  New York   Florida  Illinois
population    38332521  26448393  19651127  19552860  12882135
area            423967    695662    141297    170312    149995

In [70]:
states.values[0] #단일 인덱스 - 행

array([38332521,   423967])

In [71]:
states['area'] #열 이름 - 열열

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [72]:
states.iloc[:3, :2]

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297

In [73]:
states.loc[:'Illinois', :'pop' ]

population
California    38332521
Texas         26448393
New York      19651127
Florida       19552860
Illinois      12882135

In [75]:
student = pd.Series({'국어' : 96, '영어' : 90, '수학': 80})
p_student = student / 100
p_student

국어    0.96
영어    0.90
수학    0.80
dtype: float64

In [78]:
student1 = pd.Series({'국어':96, '영어':90, '수학':80})
student2 = pd.Series({'국어': 86, '영어':100, '수학':94})
avg_student = (student1 + student2) / 2
avg_student

국어    91.0
영어    95.0
수학    87.0
dtype: float64

In [79]:
student1 = pd.Series({'영어': np.nan, '수학':80, '국어':96})
student2 = pd.Series({'수학': 94, '영어':100})
sum_student = student1.add(student2, fill_value=0)
sum_student

국어     96.0
수학    174.0
영어    100.0
dtype: float64

In [88]:
korean = pd.Series({'s1':96, 's2':80, 's3':96})
english = pd.Series({'s1':94, 's2':100, 's3':88})
math = pd.Series({'s1':90, 's2':83, 's3':92})
score = pd.DataFrame({'kor':korean, 'eng':english, 'mat':math})
score

kor  eng  mat
s1   96   94   90
s2   80  100   83
s3   96   88   92

In [85]:
score = score/100
score

kor   eng   mat
s1  0.96  0.94  0.90
s2  0.80  1.00  0.83
s3  0.96  0.88  0.92

In [89]:
score1 = score + np.random.randint(-10, 10)
score1

kor  eng  mat
s1  101   99   95
s2   85  105   88
s3  101   93   97

In [90]:
score2 = score + np.random.randint(-10, 10)
score2

kor  eng  mat
s1  102  100   96
s2   86  106   89
s3  102   94   98

In [91]:
sum_score = score1 + score2
sum_score

kor  eng  mat
s1  203  199  191
s2  171  211  177
s3  203  187  195

In [92]:
music = pd.Series({'s1':96, 's2':98, 's3':85})
score1['mus'] = music
score1

kor  eng  mat  mus
s1  101   99   95   96
s2   85  105   88   98
s3  101   93   97   85

In [93]:
sum_score = score1 + score2
sum_score

eng  kor  mat  mus
s1  199  203  191  NaN
s2  211  171  177  NaN
s3  187  203  195  NaN